//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STG_website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public short Day { get; set; }
        public short Hour { get; set; }
        public int SchoolsId { get; set; }
        public int RoomsId { get; set; }
        public int GroupsId { get; set; }
        public int TeachersId { get; set; }
        public int LessonsId { get; set; }
    
        public virtual Schools Schools { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual Teachers Teachers { get; set; }
        public virtual Lessons Lessons { get; set; }
    }
}
